version: '3.8'

services:
  web:
    build: .
    restart: always
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      SECRET_KEY: "u8Sx4L$^*23y7hGx$9!jYF9#4RhN2g*0"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/instance
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  sqlite_data:
